### ISSUE TITLE
name 'CtrlPDU' is not defined

### ISSUE THREAD

**Issue by jarv-git** [RCayre/mirage#19]
Hi,

After installing Mirage using setup.py, when running **mirage** I got the following error:

_[...]mirage/mirage/libs/ble_utils/scapy_link_layers.py", line 28, in <module>
    split_layers(BTLE_DATA, CtrlPDU)
NameError: name 'CtrlPDU' is not defined_

I've checked the dependencies and all seem properly installed. 

Do you know where the problem is? Could it be some trouble with Scapy (mine v2.4.4)?

Thanks!

**Comment by RCayre** [comment]
Hi, thank you for opening this issue. 
Have you installed scapy from pip or directly from the official repository ? They have added support for new Link Layer PDUs recently and the CtrlPDU packet has been replaced by BTLE_CTRL. I was able to reproduce the issue with the latest version from github.

Can you tell me if the following fix solves the problem ? You can just replace mirage/libs/ble_utils/scapy_link_layers.py by the following file:
[scapy_link_layers.py.txt](https://github.com/RCayre/mirage/files/6032104/scapy_link_layers.py.txt)

I'll write a better fix for the next release.

**Comment by jarv-git** [comment]
Hi!

Yes, I've installed it directly from the official repo. 

Great, the fix solves the problem. I had also tried CtrlPDU directly from Scapy and I was getting also an error. The point was I was not able to identify the replacement.

Thank you. Nice tool BTW.
