### ISSUE TITLE
Additional Supported Devices

### ISSUE THREAD

**Issue by jarv-git** [RCayre/mirage#20]
Hi,
Regarding the Supported Devices:
- Are you planning to add support for SniffLE devices? You have API for Ubertooth, BTLEJack, NRFSniffer...as SniffLE firmware is the only one capable of sniffing BT 5, I was wondering if this is on your milestones for future releases.
- RZUSBStick is no longer available. How difficult could it be to create or modify the API to add support to other Killerbee's devices such as ApiMote? 

Thanks!

**Comment by RCayre** [comment]
Hi,
Sniffle support is a work in progress, it will probably be added in the next release.
Regarding Zigbee devices, i don't have access to an apiMote yet, and I don't plan to support it for now. 
I'm also working on a custom firmware for nRF52840 dongle allowing to interact with BLE, 802.15.4 and enhanced shockburst, stay tuned.
