### ISSUE TITLE
UserWarning: Failed to create a device file using `uinput` module

### ISSUE THREAD

**Issue by GoulongWang** [RCayre/mirage#28]
Hi RCayre, 

I followed the instruction at this [page](https://homepages.laas.fr/rcayre/mirage-documentation/cli.html), but something wrong when I entered `sudo mirage` . The message displayed

> UserWarning: Failed to create a device file using `uinput` module. Sending of events may be limited or unavailable depending on plugged-in devices

![image](https://user-images.githubusercontent.com/23274642/169014114-502ba75b-eac4-4d5d-8507-0ad253a9f08a.png)

Could you help me fix this?

My Environment : Ubuntu20.04 in Window Subsystem Linux 2

**Comment by RCayre** [comment]
Hi, thanks for reporting. 
Unfortunately, the problem is linked to keyboard library, which doesn't work on WSL. You should open an issue here: https://github.com/boppreh/keyboard

Or use a regular Linux to run Mirage.
