### ISSUE TITLE
about 'c6d' command

### ISSUE THREAD

**Issue by p1yang** [RCayre/mirage#33]
When I use the ble module, I always encounter this problem.
<img width="1017" alt="image" src="https://user-images.githubusercontent.com/82321176/210318215-0fc693ab-09d5-4497-be55-823c812d1ea0.png">

**Comment by p1yang** [comment]
system is Ubuntu 18.04.6

**Comment by RCayre** [comment]
Hi, according to the output, your dongle doesn't support Bluetooth Low Energy. You should probably use another device to use mirage.
